export enum Category {
  CONCERT = 'CONCERT',
  SPORT = 'SPORT',
  THEATRE = 'THEATRE',
  CINEMA = 'CINEMA',
  FESTIVAL = 'FESTIVAL',
  CONFERENCE = 'CONFERENCE',
  EXPOSITION = 'EXPOSITION',
  ATELIER = 'ATELIER',
}